[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.build-debug]
command = "cargo"
args = ["build"]
dependencies = ["test"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.release]
dependencies = [
    "format",
    "build",
]

[tasks.install]
script = [
    "echo \"\nInstalling casewm\" ",
    "sudo cp -v ../install-files/casewm.desktop /usr/share/xsessions",
    "sudo cp -v ../install-files/casewm_startup.sh /usr/local/bin",
    "sudo cp -v ../install-files/casewm-background.png /usr/share/backgrounds/",
    "cp -rv ../install-files/picom/ ~/.config/",
    "sudo rm -rvf /usr/local/bin/casewm",
    "sudo cp -v ../target/release/casewm /usr/local/bin",
]
dependencies = ["release"]

[tasks.reinstall]
script = [
    "echo \"\nInstalling casewm binary\" ",
    "sudo cp -v ../target/release/casewm /usr/local/bin",
]
dependencies = [ "release" ]

[tasks.uninstall]
script = [
    "echo \"\nUninstalling casewm\"",
    "rm -rvf ~/.config/picom",
    "sudo rm -rvf /usr/share/xsessions/casewm.desktop",
    "sudo rm -rvf /usr/local/bin/casewm_startup.sh",
    "sudo rm -rvf /usr/share/backgrounds/casewm-background.png",
    "sudo rm -rvf /usr/local/bin/casewm",
]
